# Introdução à Ciência de Dados - UFPB
Professor: Yuri Malheiros

## NumPy

Implemente a função `distance` abaixo. Ela deve receber dois pontos e retornar a distância euclidiana entre eles. Cada ponto é representado por um array do NumPy, por exemplo, `p1 = np.array([2,4])` representa o ponto com coordenadas x=2 e y=2.

### Artur Iury

**matricula:** 20170043750

In [140]:
import numpy as np
import math 

p1 = np.array([0,0])
p2 = np.array([1,1])

def distance(p1, p2):
    """
    >>> distance(np.array([0,0]), np.array([1,1]))
    1.4142135623730951
    
    >>> distance(np.array([1,2]), np.array([3,4]))
    2.8284271247461903
    
    >>> distance(np.array([5,2]), np.array([-2,-1]))
    7.615773105863909
    """

    # ADICIONE O SEU CÓDIGO AQUI

    h=[]
    for i in range(len(p1)):
        p= p2-p1
        h.append( math.pow(p[i],2))
        a = np.array(h)
    
        distancia = math.sqrt(np.sum(a))
    return distancia

In [141]:
distance(p1,p2)

1.4142135623730951

Implemente a função `n_distances` abaixo. Ela recebe um ponto (`p1`), como um array do NumPy, e uma lista de pontos (`points`), uma matriz do NumPy, onde cada linha representa um ponto.

Esta função deve retornar a distância de `p1` para todos os pontos da matriz `points`. O retorno também é uma matriz, onde cada linha tem a distância de `p1` para o ponto daquela linha.

In [142]:
p1 = np.array([1,2])
p2 = np.array([1,1])
points = np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]])
def n_distances(p1, points):
    """
    >>> n_distances(np.array([0,0]), np.array([[1,1]]))
    array([1.41421356])
    
    >>> n_distances(np.array([0,0]), np.array([[1,1], [2,2]]))
    array([1.41421356, 2.82842712])
    
    >>> n_distances(np.array([1,2]), np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]]))
    array([3.60555128, 1.41421356, 4.        , 9.05538514, 7.61577311])
    """
    
    # ADICIONE O SEU CÓDIGO AQUI
    p = points[0:] - p1
    x = points[0:] - p1
    h = p*x
    a = np.sum(h,axis = 1 )

    y = []
    for i in range(len(a)):
        y.append(math.sqrt(a[i]))
    n_dist = np.array(y)
    return n_dist

In [143]:
n_distances(p1, points)

array([3.60555128, 1.41421356, 4.        , 9.05538514, 7.61577311])

## Teste

In [139]:
import doctest

doctest.testmod(verbose=True)

Trying:
    distance(np.array([0,0]), np.array([1,1]))
Expecting:
    1.4142135623730951
ok
Trying:
    distance(np.array([1,2]), np.array([3,4]))
Expecting:
    2.8284271247461903
ok
Trying:
    distance(np.array([5,2]), np.array([-2,-1]))
Expecting:
    7.615773105863909
ok
Trying:
    n_distances(np.array([0,0]), np.array([[1,1]]))
Expecting:
    array([1.41421356])
ok
Trying:
    n_distances(np.array([0,0]), np.array([[1,1], [2,2]]))
Expecting:
    array([1.41421356, 2.82842712])
ok
Trying:
    n_distances(np.array([1,2]), np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]]))
Expecting:
    array([3.60555128, 1.41421356, 4.        , 9.05538514, 7.61577311])
ok
1 items had no tests:
    __main__
2 items passed all tests:
   3 tests in __main__.distance
   3 tests in __main__.n_distances
6 tests in 3 items.
6 passed and 0 failed.
Test passed.


TestResults(failed=0, attempted=6)